

# worked with versions:
ctf01d-versions:
    - v0.5.2

# part of config for jury-checker
checker-config-v0.5.2:
    id: "example_service1_py" # work directory will be checker_example_service1_py
    service_name: "Service1 Py"
    enabled: yes
    script_path: "./checker.py"
    script_wait_in_sec: 5 # max time for running script
